import {Roboto} from "next/font/google";
import {Metadata} from "next";
import Footer from "@/components/footer/footer";
import {Header} from "@/components/header/header";
import s from './layout.module.scss'

export const metadata: Metadata = {
  title: 'Posts',
  description: 'Generated by Next.js',

}

const roboto = Roboto({subsets: ['latin'], weight: ['700', '400']})

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`${roboto.className} + ${s.bodyWrapper}`}>
    <Header/>

    <main>{children}</main>

    <Footer/>
    </body>
    </html>
  )
}
